AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*_test.rb
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - test/*_test.rb
    - test/**/*_test.rb
Naming/VariableNumber:
  Exclude:
    - test/*_test.rb
    - test/**/*_test.rb
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/AccessorGrouping:
  EnforcedStyle: separated

Layout/LineLength:
  Exclude:
    - test/*_test.rb
    - test/**/*_test.rb
