name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "3.0.7"
          - "3.1.5"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run rspec
      run: bundle exec rake test

  rubocop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "3.0.7"
          - "3.1.5"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run rubocop
      run: bundle exec rubocop
