name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: "RSpec @ Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}"
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
    strategy:
      matrix:
        ruby:
          - "3.1"
          - "3.3"
          - "head"
        rails:
          - "6.1"
          - "7.1"
          - "7.2"
        exclude:
            - ruby: "3.3"
              rails: "6.1"
            - ruby: "head"
              rails: "6.1"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run rspec
      run: bundle exec rake test

  linters:
    name: "Rubocop @ Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}"
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
    strategy:
      matrix:
        ruby:
          - "head"
        rails:
          - "7.2"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run rubocop
      run: bundle exec rubocop
